import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: true,
      items: [
        'getting-started/quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsible: true,
      collapsed: true,
      items: [
        'core-concepts/architecture',
        'core-concepts/principles',
        'core-concepts/protocol-vs-implementation',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsible: true,
      collapsed: true,
      items: [
        'community/code-of-conduct',
        'community/contributing',
        'community/governance',
      ],
    },
  ],
};

export default sidebars;
